### ISSUE TITLE
Using in Console application

### ISSUE THREAD

**Issue by vyelchuri** [RickStrahl/WestwindToolkit#15]
There is any way to use ViewRenderer class in console application with out HTTP context ?

**Comment by vyelchuri** [comment]
@RickStrahl Does this project contains any test cases for the "`RenderViewToString`" ?

"`RenderViewToString`" only allows to work when it contains HTTPContext, how to create a test case with out HTTPContext ?

I have tried to create fake HTTPContext, but it was failing though when `FindView() `is executing
`HttpContext.Current = new HttpContext(
    new HttpRequest("", "http://tempuri.org", ""),
    new HttpResponse(new StringWriter())
    );`

**Comment by RickStrahl** [comment]
You really need an HttpContext for this to work. If you want to do this outside of ASP.NET, I recommend you look at ![https://github.com/RickStrahl/Westwind.RazorHosting](Westwind.RazorHosting) instead which can be run in any type of project.

**Comment by ManfredLange** [comment]
Looks as if the link is broken. Here is a link that worked as of writing: [Westwind.RazorHosting](https://github.com/RickStrahl/Westwind.RazorHosting)

**Comment by SGK1977** [comment]
@RickStrahl - I'm trying to use your code to create a controller context from a singleton inside an MVC application. Since there is no httpcontext I am creating a dummy one like this. And then I use it inside the controller context. It seems to work, but I am not sure what the cons of using a dummy httpcontext like this are. Please advise if there is an alternative approach.

HttpContext ctx = new HttpContext(
            new HttpRequest("", "http://tempuri.org", ""),
            new HttpResponse(new StringWriter())
            );

            // User is logged in
            ctx.User = new GenericPrincipal(
                new GenericIdentity("username"),
                new string[0]
                );

            // User is logged out
            ctx.User = new GenericPrincipal(
                new GenericIdentity(String.Empty),
                new string[0]
                );

            // get context wrapper from HttpContext if available
            HttpContextBase wrapper = null;
            if (ctx != null)
                wrapper = new HttpContextWrapper(ctx);
            else
                throw new InvalidOperationException(
                    "Can't create Controller Context if no active HttpContext instance is available.");
