### ISSUE TITLE
Westwind.Utilities Fails to install in VS Community 2017 Web API app 

### ISSUE THREAD

**Issue by reidsci** [RickStrahl/WestwindToolkit#18]
I am running an app that is .NetCore with a Web API, nothing else. I used the suggested installation method. That and the results follow:

PM> Install-Package Westwind.Utilities
Restoring packages for C:\Users\Main\Documents\Visual Studio 2017\Projects\mycoreupload\mycoreupload\mycoreupload.csproj...
Install-Package : Package Westwind.Utilities 2.71.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package 
Westwind.Utilities 2.71.0 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package Westwind.Utilities
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with .NETCoreApp,Version=v1.1.
At line:1 char:1
+ Install-Package Westwind.Utilities
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'mycoreupload'.
At line:1 char:1
+ Install-Package Westwind.Utilities
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by RickStrahl** [comment]
You're installing into a .NET Core project and that's not going to work as that's not a supported target.

We'll look at porting to .NET Core once .NET Standard 2.0 will be available to look at and work with.

**Comment by RickStrahl** [comment]
FWIW, West Wind Utilities is now available as a separate project with support for .NET Core 2.0.

https://github.com/RickStrahl/Westwind.Utilities
