### ISSUE TITLE
MVC ViewRenderer issue

### ISSUE THREAD

**Issue by kamsar** [RickStrahl/WestwindToolkit#2]
I believe I've found a bug in the `Westwind.Web.Mvc.ViewRenderer` implementation.

In `RenderViewToStringInternal` (line 137), it checks to see if the `viewEngineResult` is null. At least with MVC4 in my testing, the viewEngineResult is always not null. If the view path was truly not found, the result is not null but the `viewEngineResult.View` property is null.

This ends up causing an ArgumentNullException on the `ViewContext` constructor call on line 148.

I'd suggest changing the conditional to:

    if (viewEngineResult == null|| viewEngineResult.View == null)
        throw new FileNotFoundException...

Of course I might be wrong too ;)

**Comment by RickStrahl** [comment]
Sorry for missing this outstanding issue for so long. I thought I had fixed this a long time ago, but just went back and looked and sure enough it wasn't. Updated. Thanks.
