### ISSUE TITLE
Guid not serialized correctly

### ISSUE THREAD

**Issue by gabe-alex** [RickStrahl/WestwindToolkit#20]
Hello!

When using WestwindJsonSerializer to serialize something that contains a Guid (a data reader for example), the Guids are serialized as an object with length parameter instead of the guid's string.

For example:
"Guid": {Length: 36}
instead of: "Guid": "8631CF71-2948-466C-A103-5B3726341D63"

Fix suggestion:
In WestwindJsonSerializer.cs, around line 339:

else if (val is Guid)
   WriteObject(sb, val.ToString());
else

replace WriteObject with WriteString

Thanks!

**Comment by RickStrahl** [comment]
Sorry for the late, response.

I would recommend using the Json.NET Serializer. There are startup options that allow you to choose which serializer is used. The WW serializer was a workaround a long time ago before there were a lot of choices. Since then the Json.net serializer has been integrated.
