### ISSUE TITLE
ReflectionUtils.SetPropertInternal tries to write to ReadOnly properties

### ISSUE THREAD

**Issue by robvon** [RickStrahl/WestwindToolkit#21]
Current Code: Line 547 in ReflectionUtils or thereabouts:

if (Member.MemberType == MemberTypes.Property)
				((PropertyInfo)Member). pi.SetValue(Parent, Value, null);
			else
				((FieldInfo)Member).SetValue(Parent, Value);

perhaps a test: ((PropertyInfo)Member).CanWrite ?? before the SetValue

It's done that way in the StringSerializer

This issue also occurs in the "ConfigurationFileConfigurationProvider" when missingFields are set.

Regards

Rob v N
Brisbane, AUS

**Comment by RickStrahl** [comment]
Thanks Rob. This library is no longer maintained here. It's been moved to `Westwind.Utilities` here:

https://github.com/RickStrahl/Westwind.Utilities

Looks like that problem still exists there as well. Fixing now.

```cs
// Get the member
                MemberInfo Member = Parent.GetType().GetMember(PureProperty, ReflectionUtils.MemberAccess)[0];
                if (Member.MemberType == MemberTypes.Property)
                {
                    var prop = (PropertyInfo) Member;
                    if (prop.CanWrite)
                        prop.SetValue(Parent, Value, null);
                }
                else
                    ((FieldInfo)Member).SetValue(Parent, Value);
```

**Comment by robvon** [comment]
Thanks mate. Not much wind out there today eh!
